# Generated by Django 5.1.3 on 2024-12-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_department_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='doctor_images/'),
        ),
    ]
