# Generated by Django 5.1.3 on 2024-12-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='doctor_images/default.jpg', null=True, upload_to='doctor_images/'),
        ),
    ]
