# Generated by Django 5.1.3 on 2024-12-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('diagnosis_files', models.FileField(blank=True, null=True, upload_to='medical_history_files/')),
                ('medications', models.TextField(blank=True, null=True)),
                ('medications_files', models.FileField(blank=True, null=True, upload_to='medical_history_files/')),
                ('allergies', models.TextField(blank=True, null=True)),
                ('allergies_files', models.FileField(blank=True, null=True, upload_to='medical_history_files/')),
                ('treatment_history', models.TextField(blank=True, null=True)),
                ('treatment_history_files', models.FileField(blank=True, null=True, upload_to='medical_history_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='adminapp.patient')),
            ],
        ),
    ]
