# Generated by Django 5.1.3 on 2024-12-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
                ('medication', models.TextField()),
                ('test_needed', models.TextField()),
                ('next_consultation_date', models.DateField()),
                ('medical_tips', models.TextField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminapp.appointment')),
            ],
        ),
    ]
